archi_desc: Bi-GRU 64 + Dropout 0.5
batch_size: 1024
layers: '[(''InputLayer'', {}), (''Embedding'', {''output_dim'': 200}), (''Bidirectional'',
  {}), (''GRU'', {''units'': 64}), (''Dropout'', {''rate'': 0.5}), (''Dense'', {''units'':
  1})]'
model_name: Archi301
sample_size: 100000
