archi_desc: Bi-LSTM 32 + Dense 10
batch_size: 1024
layers: '[(''InputLayer'', {}), (''Embedding'', {''output_dim'': 200}), (''Bidirectional'',
  {}), (''LSTM'', {''units'': 32}), (''Dense'', {''units'': 10}), (''Dense'', {''units'':
  1})]'
model_name: Archi401
sample_size: 100000
