archi_desc: GRU 32 + Dropout 0.5
batch_size: 4096
layers: '[(''InputLayer'', {}), (''Embedding'', {''output_dim'': 200}), (''GRU'',
  {''units'': 32}), (''Dropout'', {''rate'': 0.5}), (''Dense'', {''units'': 1})]'
model_name: Archi300
sample_size: 1452791
