archi_desc: Bi-LSTM 64 + Dropout 0.5
batch_size: 4096
layers: '[(''InputLayer'', {}), (''Embedding'', {''output_dim'': 200}), (''Bidirectional'',
  {}), (''LSTM'', {''units'': 64}), (''Dropout'', {''rate'': 0.5}), (''Dense'', {''units'':
  1})]'
model_name: Archi201
sample_size: 1452791
