archi_desc: Bi-LSTM 64 + Dense 24
batch_size: 1024
layers: '[(''InputLayer'', {}), (''Embedding'', {''output_dim'': 200}), (''Bidirectional'',
  {}), (''LSTM'', {''units'': 64}), (''Dense'', {''units'': 24}), (''Dense'', {''units'':
  1})]'
model_name: Archi202
sample_size: 100000
