archi_desc: Bi-GRU 64 + Dense 24
batch_size: 1024
layers: '[(''InputLayer'', {}), (''Embedding'', {''output_dim'': 200}), (''Bidirectional'',
  {}), (''GRU'', {''units'': 64}), (''Dense'', {''units'': 24}), (''Dense'', {''units'':
  1})]'
model_name: Archi302
sample_size: 100000
