archi_desc: Simple RNN 32 + Dropout 0.5
batch_size: 1024
layers: '[(''InputLayer'', {}), (''Embedding'', {''output_dim'': 200}), (''SimpleRNN'',
  {''units'': 32}), (''Dropout'', {''rate'': 0.5}), (''Dense'', {''units'': 1})]'
model_name: Archi100
sample_size: 100000
