archi_desc: Dense 32 + Dropout 0.5
batch_size: 1024
layers: '[(''InputLayer'', {}), (''Dense'', {''units'': 32}), (''Dropout'', {''rate'':
  0.5}), (''Dense'', {''units'': 1})]'
model_name: Archi000
sample_size: 100000
